/**
 *
 *  inline-source-map
 *  将会捕捉到抛出的错误
 *  位于 print.js 第 9 行
 *
 */
(() => {
  console.error('TEST_ERROR>>>>>CATCH')
})();